pod 'MBProgressHUD', '~> 0.9.1'
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
pod 'KVOController'
pod 'SDWebImage'
pod 'Mantle'
pod 'MJRefresh'

pod 'OpenSSL-Universal', :podspec => 'https://raw.github.com/krzyzanowskim/OpenSSL/master/OpenSSL-Universal.podspec'

pod 'WebViewJavascriptBridge'